### ISSUE TITLE
Unable to pull image from wurstmeister/kafka-docker

### ISSUE THREAD

**Issue by bryanleekw** [speedd-project/speedd-docker#1]
I tried to pull the docker image from docker hub, but failed. I followed the steps in github (https://github.com/speedd-project/speedd-docker)

root@nb1:/proj/speedd/speedd-docker-master# docker-compose -f docker-compose.yml -f docker-compose-ccf.yml up -d
Pulling kafka (wurstmeister/kafka-docker:latest)...
ERROR: repository wurstmeister/kafka-docker not found: does not exist or no pull access
root@nb1:/proj/speedd/speedd-docker-master# docker-compose -f docker-compose.yml -f docker-compose-tm.yml up -d
Pulling kafka (wurstmeister/kafka-docker:latest)...
ERROR: repository wurstmeister/kafka-docker not found: does not exist or no pull access
root@nb1:/proj/speedd/speedd-docker-master# docker

Would anyone help me what I have done wrongly.

**Comment by ishkin** [comment]
Speed dockers are built using the kafka docker,
In the prerequisite you should have pulled and built the kafka docker, specifically the section

git clone https://github.com/speedd-project/kafka-docker.git
cd kafka-docker
docker build -t wurstmeister/kafka-docker --rm=true .

So if this went by ok, you should have a wurstmeister/kafka-docker:latest image (can check with d**ocker images** command)

**Comment by bryanleekw** [comment]
thank you ishkin

root@nb1:/proj/speedd/speedd-docker-master/kafka-docker# docker build -t wurstmeister/kafka-docker --rm=true .
Sending build context to Docker daemon  175.6kB
Step 1/16 : FROM ubuntu:trusty
 ---> d6ed29ffda6b
Step 2/16 : MAINTAINER Wurstmeister
 ---> Using cache
 ---> 7f844453aac2
Step 3/16 : RUN echo 'root:speedd' | chpasswd
 ---> Using cache
 ---> f7b9eada4c08
Step 4/16 : ENV KAFKA_VERSION "0.8.2.1" SCALA_VERSION "2.10"
 ---> Using cache
 ---> 534eb9592772
Step 5/16 : RUN apt-get update && apt-get install -y unzip openjdk-6-jdk wget curl git docker.io jq
 ---> Using cache
 ---> 5dd57f78f767
Step 6/16 : ADD download-kafka.sh /tmp/download-kafka.sh
 ---> Using cache
 ---> 9393578170e5
Step 7/16 : RUN chmod 776 /tmp/download-kafka.sh
 ---> Using cache
 ---> 7227390b83c5
**Step 8/16 : RUN /tmp/download-kafka.sh
 ---> Running in e648f8a296ae
The command '/bin/sh -c /tmp/download-kafka.sh' returned a non-zero code: 8** 

but when I tried to run docker build, and failed.

**Comment by ishkin** [comment]
Hello Bryan,
I am sorry but I cannot help you with that, this is a kafka docker image (built from kafka repository) and not something speedd has provided. You need to investigate the reason why download-kafka.sh fails on your docker environment.

The only thing I can provide after quick googling is this https://github.com/wurstmeister/kafka-docker/issues/142

Perhaps this will help.

**Comment by bryanleekw** [comment]
thanks.. I found out that this is related to apache no longer provide 0.8.2.1 kafka in their repository, so I modify the download path to newer version, such as 0.10.2.1, and now works.
